CREATE TABLE chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL CHECK (type IN ('DIRECT', 'GROUP')),
    title VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE chat_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMP,
    CONSTRAINT fk_chat_participant_chat
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
    CONSTRAINT uq_chat_user UNIQUE (chat_id, user_id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    content TEXT NOT NULL CHECK (LENGTH(TRIM(content)) > 0),
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_chat_message
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_participant
    FOREIGN KEY (participant_id) REFERENCES chat_participants(id) ON DELETE RESTRICT
);

CREATE INDEX idx_participants_chat_id ON chat_participants(chat_id);
CREATE INDEX idx_participants_user_id ON chat_participants(user_id);
CREATE INDEX idx_messages_chat_sent ON messages(chat_id, sent_at DESC);
CREATE INDEX idx_messages_participant ON messages(participant_id);