spring:
  config:
    import:
      - optional:file:./.env[.properties]
      - optional:file:../.env[.properties]
  profiles:
    active: dev
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:h2:mem:authdb}
    driver-class-name: ${AUTH_DB_DRIVER:org.h2.Driver}
    username: ${AUTH_DB_USER:sa}
    password: ${AUTH_DB_PASSWORD:password}
  flyway:
    enabled: true
    locations: classpath:db/migrations
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
          schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
          auto.register.schemas: true
    admin:
      auto-create: true

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30000000}
    refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:252000000}

server:
  port: ${AUTH_SERVICE_PORT:9001}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
