CREATE TABLE profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  nickname VARCHAR(100),
  username VARCHAR(100),
  email VARCHAR(100),
  bio TEXT,
  birth_date VARCHAR(100),
  profile_color VARCHAR(30) NOT NULL DEFAULT 'VIOLET_GRADIENT'
      CONSTRAINT chk_profiles_color CHECK (profile_color IN (
         'VIOLET_GRADIENT', 'INDIGO_GRADIENT', 'FUCHSIA_GRADIENT',
         'PINK_GRADIENT', 'ORANGE_GRADIENT', 'AMBER_GRADIENT',
         'BI_COLOR_VIOLET_ORANGE', 'BI_COLOR_FUCHSIA_AMBER'
      ))
);

INSERT INTO profiles (user_id, nickname, username, email)
VALUES (1, 'big', 'big', 'big@gmail.com');

INSERT INTO profiles (user_id, nickname, username, email)
VALUES (2, 'pig', 'pig', 'pig@gmail.com');