version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=min_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
