services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=min_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    container_name: bp-min-db
    networks:
      - bp-min

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: bp-min-redis
    networks:
      - bp-min
    volumes:
       - ./redis-data:/data

  client:
    build: ./client
    ports:
      - "5173:5173"
    container_name: bp-min-client
    networks:
      - bp-min
    depends_on:
       - redis
       - pg_db

networks:
  bp-min:
    driver: bridge