spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5435/min_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect