spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5435/min_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
security:
  jwt:
    secret_key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
    access_token_expiration: 30_000 # 30 seconds
    refresh_token_expiration: 252_000_000 # 7 days