spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5435/min_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
security:
  jwt:
    secret_key: YOUR_SECRET_KEY
    access_token_expiration: 30_000_000 # 30 seconds
    refresh_token_expiration: 252_000_000 # 7 days
logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: TRACE

app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
    allowed-methods:
      - "GET"
      - "POST"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
    allow-credentials: true
    max-age: 3600