CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nickname VARCHAR(100) NOT NULL,
                       username VARCHAR(100) NOT NULL,
                       password VARCHAR(100) NOT NULL,
                       email VARCHAR(100) NOT NULL,
                       CONSTRAINT uk_users_username UNIQUE (username)
);

INSERT INTO users (nickname, username, password, email)
VALUES ('big', 'big', '$2a$12$PGjbxudCF1McUG4T1eODtOOn4nz.Ryipm8Pw.vPWiDvqW8EAx7q2q', 'big@gmail.com');

INSERT INTO users (nickname, username, password, email)
VALUES ('pig', 'pig', '$2a$12$PGjbxudCF1McUG4T1eODtOOn4nz.Ryipm8Pw.vPWiDvqW8EAx7q2q', 'pig@gmail.com');